[DEFAULT]
root_dir=data\TestSamples

[floss]
floss_filename=flossresults_reduced_7.json

[models]
string_model=featgenerator\256_pipeline.pickle

[exif]
exif_filename=exiftool_results.json
exif_binary=bins\exiftool.exe

[groundtruth]
adversary_mapping=data\CampaignGroupTags_TestSet.csv
#adversary_mapping=data\ADAPTDataset.csv

[lief]
lief_filename=lief_features.json

[yara]
malcat_filename=malcatYaraResults.json

[regex]
regex_filename=regex_results.json

[oletool]
oletool_filename=oletool_features_updated.json

[censys]
censys_filename=censys_features_withhostdata.json
